proxy:
  pypydance-api: ""
  youtube-video: ""
  youtube-api: ""
  youtube-image: ""
keys:
  youtube-api: ""
youtube:
  enable-youtube-api: false
  enable-youtube-thumbnail: false
  enable-youtube-video: false
preload:
  max-preload-count: 4
download:
  max-parallel-download-count: 2
cache:
  path: "./cache"
  max-cache-size: 300
  keep-favorites: false
  whitelist: []
db:
  path: ./data.db
